import assert from 'node:assert/strict';
import {freshGame,restoreGame,act,tick,income,totalTroops} from '../dist/game.js';
let checks=0;
const test=(name,fn)=>{fn();checks++;console.log('PASS',name);};
test('Construction spends exactly once, rejects overlap, completes and changes production',()=>{const s=freshGame(),before=income(s).food;assert(act(s,'build',{key:'farm'}).ok);assert.equal(s.resources.gold,1040);const gold=s.resources.gold;assert(!act(s,'build',{key:'farm'}).ok);assert.equal(s.resources.gold,gold);tick(s,27);assert.equal(s.buildings.farm,2);assert.equal(income(s).food,before+90);});
test('Recruitment validates and queues sequentially',()=>{const s=freshGame();assert(!act(s,'recruit',{key:'knight',count:5}).ok);assert(!act(s,'recruit',{key:'sword',count:-5}).ok);assert(act(s,'recruit',{key:'sword',count:5}).ok);assert(act(s,'recruit',{key:'spear',count:5}).ok);assert.equal(s.queue[1].start,s.queue[0].end);tick(s,7);assert.equal(s.troops.sword,25);assert.equal(s.troops.spear,12);tick(s,6);assert.equal(s.troops.spear,17);});
test('Trade agreement cannot charge twice and war ends commerce',()=>{const s=freshGame();const before=income(s).gold;assert(act(s,'diplomacy',{target:'willow',action:'trade'}).ok);assert.equal(income(s).gold,before+65);const gold=s.resources.gold;assert(!act(s,'diplomacy',{target:'willow',action:'trade'}).ok);assert.equal(s.resources.gold,gold);assert(act(s,'diplomacy',{target:'willow',action:'war'}).ok);assert.equal(s.relations.willow.trade,false);});
test('Army leaves, conquers camp, survives and returns',()=>{const s=freshGame(),before=totalTroops(s.troops);assert(act(s,'march',{target:'bandits',fraction:.75}).ok);assert(totalTroops(s.troops)<before);tick(s,30);assert.equal(s.places.find(p=>p.id==='bandits').owner,'player');assert.equal(s.marches[0].returning,true);tick(s,30);assert.equal(s.marches.length,0);assert(totalTroops(s.troops)<before);assert(totalTroops(s.troops)>30);});
test('Independent state requires war and peace recalls marching army',()=>{const s=freshGame();assert(!act(s,'march',{target:'willow',fraction:1}).ok);act(s,'diplomacy',{target:'willow',action:'war'});assert(act(s,'march',{target:'willow',fraction:1}).ok);act(s,'diplomacy',{target:'willow',action:'peace'});tick(s,30);assert.equal(s.places.find(p=>p.id==='willow').owner,'willow');tick(s,30);assert.equal(totalTroops(s.troops),46);});
test('Events begin and finish, resources never underflow',()=>{const s=freshGame();tick(s,91);assert(s.events.some(e=>e.type==='drought'));tick(s,71);assert(!s.events.some(e=>e.type==='drought'));tick(s,80);assert(s.events.some(e=>e.type==='invasion'));tick(s,46);assert(s.flags.raided);assert(Object.values(s.resources).every(v=>v>=0));});
test('Ritual creates beast, resolves and weakens hostile city',()=>{const s=freshGame();s.resources={gold:9000,wood:9000,stone:9000,food:9000};s.buildings.shrine=1;act(s,'diplomacy',{target:'red',action:'war'});assert(act(s,'summon').ok);assert(!act(s,'summon').ok);tick(s,46);assert(s.beast);tick(s,31);assert.equal(s.beast,null);assert.equal(s.places.find(p=>p.id==='red').defense,92);});
test('Political victory and continue',()=>{const s=freshGame();s.resources.gold=5000;for(const target of ['willow','oak','gold','red'])act(s,'diplomacy',{target,action:'alliance'});assert.equal(s.victory,'Политическая победа');assert.equal(s.speed,0);assert(act(s,'continue').ok);tick(s,1);assert.equal(s.victory,null);});
test('Economic and military victories',()=>{const s=freshGame();s.resources.gold=6500;for(const target of ['willow','oak','gold'])act(s,'diplomacy',{target,action:'trade'});tick(s,1);assert.equal(s.victory,'Экономическая победа');const a=freshGame();a.places.filter(p=>p.kind==='city').forEach(p=>p.owner='player');tick(a,1);assert.equal(a.victory,'Военная победа');});
test('Pause and save roundtrip including queued action',()=>{const s=freshGame();act(s,'build',{key:'market'});const round=restoreGame(JSON.stringify(s));assert.deepEqual(round,s);s.speed=0;tick(s,50);assert.equal(s.time,0);assert.equal(restoreGame('{bad'),null);const bad=freshGame();bad.resources.gold=-1;assert.equal(restoreGame(JSON.stringify(bad)),null);});
console.log(`${checks} game scenarios passed`);

