import test from 'node:test';import assert from 'node:assert/strict';
import {Room} from '../rooms.mjs';import {UNITS,counterPower,armySpeed,totalTroops,income} from '../dist/game.js';
import {findRoute,routeLength} from '../dist/navigation.js';import {tickSkirmishes} from '../skirmishes.mjs';
const setup=()=>{const r=new Room('a','Первый',0);r.join('b','Второй');r.lobby('b',{action:'ready'});r.seed=1329;r.start('a');return r;};
test('closed slots remain closed across joining, kicking and adding or removing specific bots',()=>{
 const r=new Room('a','Хост',0);assert.ok(r.lobby('a',{action:'slot',slot:2}).ok);assert.equal(r.lobby('a',{action:'slot',slot:-1}).ok,false);r.join('b','B');r.join('c','C');assert.equal(r.members.find(m=>m.session==='c').slot,3);assert.equal(r.join('d','D').ok,false);r.lobby('a',{action:'kick',id:'r1'});assert.ok(r.join('d','D').ok);assert.equal(r.members.find(m=>m.session==='d').slot,1);assert.equal(new Set(r.members.map(m=>m.id)).size,3);
 const bots=new Room('x','Хост',2);bots.lobby('x',{action:'difficulty',index:1,value:'hard'});bots.lobby('x',{action:'bots',count:1,index:0});assert.deepEqual(bots.botDifficulties,['hard']);assert.deepEqual(bots.botSlots,[2]);bots.lobby('x',{action:'bots',count:0});assert.deepEqual(bots.botSlots,[]);
});
test('lobby enforces readiness, host permissions, bot capacity and difficulty',()=>{
 const r=new Room('a','Хост',0);assert.ok(r.join('b','Друг').ok);assert.equal(r.start('a').ok,false);assert.equal(r.lobby('b',{action:'bots',count:1}).ok,false);assert.ok(r.lobby('a',{action:'bots',count:2}).ok);assert.equal(r.join('c','Лишний').ok,false);assert.ok(r.lobby('a',{action:'difficulty',index:1,value:'hard'}).ok);assert.equal(r.lobby('a',{action:'difficulty',index:1,value:'cheat'}).ok,false);r.lobby('b',{action:'ready'});assert.ok(r.start('a').ok);assert.equal(r.members.filter(m=>m.bot).length,2);assert.equal(r.members.find(m=>m.bot&&m.difficulty==='hard').difficulty,'hard');assert.equal(r.lobby('a',{action:'map',value:'hills'}).ok,false);
});
test('spawn seed varies assignments but all four starts have equal nearby resources and center access',()=>{
 const assignments=new Set();for(const map of ['valley','forest','hills'])for(const seed of [1329,9000,120000,400000]){const r=new Room('a','Хост',3,map);r.seed=seed;r.start('a');assignments.add(r.actor('a').home);assert.equal(r.places.length,9);assert.equal(r.places.filter(p=>p.kind==='village'&&!p.strategic).length,2);const starts=r.members.map(m=>r.places.find(p=>p.id===m.home));for(const kind of ['village']){const distances=starts.map(p=>Math.min(...r.places.filter(n=>n.kind===kind&&!n.strategic).map(n=>routeLength(findRoute(p,n,r.places,r.map)))));assert.ok(Math.max(...distances)-Math.min(...distances)<2,kind+': '+distances.join(','));}const center=r.places.find(p=>p.strategic);const distances=starts.map(p=>routeLength(findRoute(p,center,r.places,r.map)));assert.ok(Math.max(...distances)-Math.min(...distances)<3,'center: '+distances.join(','));for(const s of r.actors)assert.deepEqual(s.resources,{gold:1200,wood:760,stone:520,food:980});}assert.ok(assignments.size>1);
});
test('three tiers retain hard counters, elites need technology, cavalry share increases speed',()=>{
 assert.deepEqual([...new Set(Object.values(UNITS).map(u=>u.tier))].sort(),[1,2,3]);const r=setup(),s=r.actor('a');s.buildings.barracks=3;s.resources.gold=10000;assert.equal(r.command('a','recruit',{key:'guard',count:5}).ok,false);s.techs.tactics=1;assert.ok(r.command('a','recruit',{key:'guard',count:5}).ok);assert.ok(counterPower({spear:40},{paladin:20},s)>counterPower({spear:40},{sword:20},s));assert.ok(counterPower({paladin:20},{spear:40},s)<counterPower({paladin:20},{archer:40},s));assert.ok(armySpeed({sword:95,knight:5})>armySpeed({sword:100}));assert.ok(armySpeed({knight:100})>armySpeed({sword:95,knight:5})*1.3);
});
test('chosen reinforcement units conserve types, reject forged counts and arrive through routes',()=>{
 const r=setup(),s=r.actor('a'),p=r.places.find(p=>p.id==='willow');p.owner=s.playerId;p.garrison={spear:3};r.refresh();const before=totalTroops(s.troops)+totalTroops(p.garrison),resources={...s.resources};assert.equal(r.command('a','reinforce',{target:p.id,units:{sword:100000}}).ok,false);assert.equal(r.command('a','reinforce',{target:p.id,units:JSON.parse('{"__proto__":5}')}).ok,false);assert.deepEqual(s.resources,resources);assert.ok(r.command('a','reinforce',{target:p.id,units:{sword:7,archer:4},stance:'passive'}).ok);const m=s.marches[0];assert.deepEqual(m.troops,{sword:7,archer:4});assert.equal(m.stance,'passive');assert.ok(m.route.length>2);r.tick(m.duration+.1);assert.equal(p.garrison.sword,7);assert.equal(p.garrison.archer,4);assert.equal(totalTroops(s.troops)+totalTroops(p.garrison),before);
});
test('hostile armies react locally, passive ignores incidental enemies and orders resume',()=>{
 const r=setup(),a=r.actor('a'),b=r.actor('b');r.command('a','diplomacy',{target:b.home,action:'war'});const path=[{x:-12,z:0},{x:-10,z:0}];a.marches=[{id:'a',route:path,origin:a.home,target:b.home,troops:{sword:40},start:0,end:100,duration:100,stance:'passive'}];b.marches=[{id:'b',route:path,origin:b.home,target:a.home,troops:{sword:40},start:0,end:100,duration:100,stance:'passive'}];tickSkirmishes(r,.1);assert.equal(a.marches[0].encounter,undefined);b.marches[0].stance='aggressive';tickSkirmishes(r,.1);assert.equal(a.marches[0].encounter.enemy,'b');assert.ok(totalTroops(a.marches[0].troops)<40);const originalTarget=a.marches[0].target;r.time=11;tickSkirmishes(r,.1);assert.equal(a.marches[0].encounter,null);assert.equal(a.marches[0].target,originalTarget);
});


